Remove unused variables
Error: COMPILER_WARNING:
woff2-1.0.2/src/normalize.cc: scope_hint: In function 'bool woff2::FixChecksums(woff2::Font*)'
woff2-1.0.2/src/normalize.cc:216:12: warning: variable 'head_checksum' set but not used [-Wunused-but-set-variable]
   uint32_t head_checksum = 0;
            ^~~~~~~~~~~~~
  214|     StoreU32(0, &offset, head_buf);
  215|     uint32_t file_checksum = 0;
  216|->   uint32_t head_checksum = 0;
  217|     for (auto& i : font->tables) {
  218|       Font::Table* table = &i.second;

Error: CLANG_WARNING:
woff2-1.0.2/src/normalize.cc:226:7: note: Value stored to 'head_checksum' is never read
      head_checksum = table->checksum;
      ^               ~~~~~~~~~~~~~~~
  224|
  225|       if (table->tag == kHeadTableTag) {
  226|->       head_checksum = table->checksum;
  227|       }
  228|     }

Error: CLANG_WARNING:
woff2-1.0.2/src/woff2_dec.cc:306:3: note: Value stored to 'offset' is never read
  offset = Store16(dst, offset, y_max);
  ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  304|     offset = Store16(dst, offset, y_min);
  305|     offset = Store16(dst, offset, x_max);
  306|->   offset = Store16(dst, offset, y_max);
  307|   }
  308|

Error: CLANG_WARNING:
woff2-1.0.2/src/woff2_enc.cc:339:22: note: Value stored to 'transformed_data' during its initialization is never read
      const uint8_t* transformed_data = src_table.data;
                     ^~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~
  337|         table.src_length = src_table.length;
  338|         table.transform_length = src_table.length;
  339|->       const uint8_t* transformed_data = src_table.data;
  340|         const Font::Table* transformed_table =
  341|             font.FindTable(src_table.tag ^ 0x80808080);

Error: COMPILER_WARNING:
woff2-1.0.2/src/woff2_enc.cc: scope_hint: In function 'bool woff2::ConvertTTFToWOFF2(const uint8_t*, size_t, uint8_t*, size_t*, const woff2::WOFF2Params&)'
woff2-1.0.2/src/woff2_enc.cc:339:22: warning: variable 'transformed_data' set but not used [-Wunused-but-set-variable]
       const uint8_t* transformed_data = src_table.data;
                      ^~~~~~~~~~~~~~~~
  337|         table.src_length = src_table.length;
  338|         table.transform_length = src_table.length;
  339|->       const uint8_t* transformed_data = src_table.data;
  340|         const Font::Table* transformed_table =
  341|             font.FindTable(src_table.tag ^ 0x80808080);

Error: CLANG_WARNING:
woff2-1.0.2/src/woff2_enc.cc:346:9: note: Value stored to 'transformed_data' is never read
        transformed_data = transformed_table->data;
        ^                  ~~~~~~~~~~~~~~~~~~~~~~~
  344|           table.flags |= kWoff2FlagsTransform;
  345|           table.transform_length = transformed_table->length;
  346|->         transformed_data = transformed_table->data;
  347|
  348|         }

Error: CLANG_WARNING:
woff2-1.0.2/src/woff2_enc.cc:426:18: note: Value stored to 'table_length' during its initialization is never read
        uint32_t table_length =
                 ^~~~~~~~~~~~
  424|           uint32_t table_offset =
  425|             table.IsReused() ? table.reuse_of->offset : table.offset;
  426|->         uint32_t table_length =
  427|             table.IsReused() ? table.reuse_of->length : table.length;
  428|           std::pair<uint32_t, uint32_t> tag_offset(table.tag, table_offset);

Error: COMPILER_WARNING:
woff2-1.0.2/src/woff2_enc.cc:426:18: warning: unused variable 'table_length' [-Wunused-variable]
         uint32_t table_length =
                  ^~~~~~~~~~~~
  424|           uint32_t table_offset =
  425|             table.IsReused() ? table.reuse_of->offset : table.offset;
  426|->         uint32_t table_length =
  427|             table.IsReused() ? table.reuse_of->length : table.length;
  428|           std::pair<uint32_t, uint32_t> tag_offset(table.tag, table_offset);